import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "learn Next",
  description: "Generated by create next app",
};

// layout dh mlf byzhr feh kol ma yndrg ta7to we lw 3mlna layout fe al file htb2a saf7a lwa7dha
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav style={{
          width: '100%',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          gap: '15px',
          background: 'teal',
          fontSize: '50px',
        }}>
          <Link href="/">Home</Link>
          <Link href="/articles">Articles</Link>
          <Link href="/posts">Posts</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
